Fix scroll to bottom
sparcs-kaist/taxi-front pull request #106
Opened 2022-05-03 15:27 UTC by 0ev

2022-05-03 16:21 UTC, 14KGun requested changes

2022-05-03 16:21 UTC, 14KGun commented on src/components/Chatting/Chatting.jsx
> +    var box = document.getElementsByClassName("chattingMessagesBox")[0];
js에서 var의 사용을 추천드리지 않습니다.
(var을 사용하면 안되는 이유: https://hoondev.tistory.com/101)

또는 리액트에서는 classname으로 element를 가져오기보다는 useRef를 사용하여 element를 가져올 수 있습니다.

2022-05-04 05:33 UTC, 0ev commented on src/components/Chatting/Chatting.jsx
> +    var box = document.getElementsByClassName("chattingMessagesBox")[0];
앗 죄송합니다ㅜㅠㅠ 또 같은 실수를 했네요ㅠㅠ 바로 고치겠습니다

2022-05-04 06:16 UTC, 0ev commented on src/components/Chatting/Chatting.jsx
> +    var box = document.getElementsByClassName("chattingMessagesBox")[0];
수정 완료했습니다!

2022-05-10 10:25 UTC, T-dubb reviewed
looks good!
But there are some conflicts, we should resolve.

2022-05-10 13:06 UTC, merged