#115 Fix Setting to MyPage & Fix navigation bar
sparcs-kaist/taxi-front pull request #117
Opened 2022-05-10 16:00 UTC by imYourChoi

# Summary 

- 설정을 내 페이지로 변경
- svg들을 mui icon으로 변경

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? n
- Needs to execute in order to review? n

# Images 

# Further Work 

- 스팍스 로고 제외한 모든 svg 삭제

2022-05-11 15:54 UTC, 14KGun requested changes

2022-05-15 14:19 UTC, imYourChoi commented on src/components/MyPage/MyPage.jsx
> +import svgSparcs from "../asset/sparcs_logo.svg";
수정하였습니다

2022-05-15 14:19 UTC, imYourChoi commented on src/components/Frame/Navigation.jsx
> +import { useHistory } from "react-router";
수정하였습니다

2022-05-16 12:51 UTC, 14KGun requested changes

2022-05-16 12:51 UTC, 14KGun commented on src/components/Frame/Navigation.jsx
> +        onClick={() => history.push(props.to)}
이 부분은 지워져도 좋을 것 같아요

2022-05-16 13:54 UTC, imYourChoi commented on src/components/Frame/Navigation.jsx
> +        onClick={() => history.push(props.to)}
수정하였습니다

2022-05-17 08:52 UTC, 14KGun approved these changes
수고하셨습니당~~~

2022-05-18 00:04 UTC, merged