Fix to enable searching all rooms  when no search options
sparcs-kaist/taxi-front pull request #122
Opened 2022-05-24 11:34 UTC by imYourChoi

# Summary 

It closes #111.
검색 조건을 선택하지 않았을 때 "모든 방 찾기"라는 문구가 뜨고 모든 방을 검색할 수 있도록 함.
하지만 백엔드의 api가 수정되지 않을 상태라 추후 merge

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? n
- Needs to execute in order to review? n

# Images 

# Further Work 

- 백엔드에서 API 수정 필요

2022-05-25 08:45 UTC, 14KGun commented on src/components/Search/Search/Search.jsx
> +    console.log(valueName, valuePlace[0], valuePlace[1], date.toISOString());
지우셔야 할 것 같아요~

2022-05-30 09:33 UTC, imYourChoi commented on src/components/Search/Search/Search.jsx
> +    console.log(valueName, valuePlace[0], valuePlace[1], date.toISOString());
지웠습니다~

2022-07-06 13:09 UTC, 14KGun requested changes

2022-07-06 13:09 UTC, 14KGun commented on src/components/Search/Search/Search.jsx
>        await axios
검색 조건이 없으면 아래 axios와 if 문 안의 axios가 함께 호출되는 것 같아요

2022-07-12 14:11 UTC, 14KGun approved these changes

2022-07-12 14:25 UTC, merged