#166 change location scheme
sparcs-kaist/taxi-front pull request #177
Opened 2022-08-12 09:14 UTC by GrasshopperBears

# Summary 

It closes #166

장소 관련 정보를 locations API를 통해 가져오고 표시하도록 변경했습니다.

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

### 한 곳만 선택

![image](https://user-images.githubusercontent.com/34625313/184323044-cd2ca190-65b7-4a40-8b8f-cbd9224dad28.png)

### 같은 곳 선택

![image](https://user-images.githubusercontent.com/34625313/184323077-c8d17df8-6edc-42cf-9bdf-c121e8a4eee5.png)

### 선택 후 검색 결과

![image](https://user-images.githubusercontent.com/34625313/184323108-aa239926-10ab-4587-b0e5-4ee87f21bd2e.png)

### 방 개설하기 페이지

![image](https://user-images.githubusercontent.com/34625313/184323150-49b30f95-f407-4c23-a02e-09b135ac732d.png)

# Further Work 

- 한/영 전환 지원

2022-08-13 01:57 UTC, 14KGun requested changes
수고하셨습니다 !!!!!

2022-08-13 01:57 UTC, 14KGun commented on src/components/common/roomOptions/Place.jsx
> -];
시원하네요 ㅎㅎㅎ

2022-08-13 01:57 UTC, 14KGun commented on src/components/Search/Search.jsx
> +            to: valuePlace[1]._id,
`valuePlace[0]`과 `valuePlace[1]`이 `null` 인 상황에서 error가 발생할 것 같아요 ㅜㅜ

2022-08-13 05:53 UTC, GrasshopperBears commented on src/components/Search/Search.jsx
> +            to: valuePlace[1]._id,
고맙습니다! 수정했어요 :)

2022-08-13 09:28 UTC, 14KGun approved these changes
수고하셨습니다 !!!! 👍

2022-08-13 09:28 UTC, 14KGun commented on src/components/Search/Search.jsx
> +        .get("rooms/v2/search", {
api 요청 중 하나가 `rooms/search`를 아직 사용하고 있어요.

그리고 아직 RoomElement 컴포넌트가 검색 결과에 사용되어, 조건 포함 검색시
> Error: Objects are not valid as a React child (found: object with keys {_id, enName, koName}). If you meant to render a collection of children, use an array instead.

에러가 뜨네요 ㅜㅜ 검색 결과 리펙토링에서 수정되어야 할 듯 합니다 ㅜㅜ

모든 방 검색하기 api 요청 v2로 수정하시고 머지하셔도 좋을 것 같습니당 ㅎㅎ

2022-08-13 12:23 UTC, GrasshopperBears commented on src/components/Search/Search.jsx
> +        .get("rooms/v2/search", {
위 사항+수정하면서 발견한 방 생성 관련 버그들도 fix했습니다
- 시간을 ISO string으로 변환해서 전송
- 현재시간 이전으로 방 생성 불가

2022-08-14 14:37 UTC, merged

2022-08-14 18:24 UTC, withSang commented
수고하셨습니다 ❤️ 
지금 모바일에서 돌려보니까 검색 결과 페이지에서 아래와 같은 오류가 발생했었어요! 이 브랜치 복원해서 해당 문제를 수정하는 커밋 넣어둘게요.
> Error: Objects are not valid as a React child (found: object with keys {_id, enName, koName}). If you meant to render a collection of children, use an array instead.