#167 add room modal
sparcs-kaist/taxi-front pull request #183
Opened 2022-08-16 12:40 UTC by GrasshopperBears

# Summary 

It closes #167 

방을 선택할 경우 모달을 띄우고 참가를 요청할 수 있게 함

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

![localhost_3000_search(iPhone 12 Pro)](https://user-images.githubusercontent.com/34625313/184881691-6d907df6-73fc-4941-a36d-ec701f803536.png)

# Further Work 

- Do something...

2022-08-17 17:22 UTC, 14KGun requested changes
수고하셨습니다!!!!!! 👍 👍 👍

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/SideResult.jsx
>                  key={index}
위와 동일하게 `key={room._id}` 로 수정되면 좋을 것 같아요!!

2022-08-17 17:22 UTC, 14KGun commented on src/components/common/RLayout.jsx
> +          maxWidth: "100%",
새로운 property가 추가된 이유가 있을까용????

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +      <Title>{roomInfo.name}</Title>
Title 컴포넌트는 최초 제작의도(??)에 따라 스스로 화면에 가운데 정렬하려는 특성을 가지고 있습니다.
이러한 특성을 없애고 사용하고 싶으시면 `marginAuto={false}`를 prop에 추가하시면 됩니다!!

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +      <Title>{roomInfo.name}</Title>
`marginAuto`가 `true`이면 `RLayout.R1`으로 감싸집니다 ㅜㅜㅜ

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +      <Title>{roomInfo.name}</Title>
`marginAuto`가 `true`이면 `RLayout.R1`으로 감싸집니다 ㅜㅜㅜ

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +  }, [roomInfo]);
`useEffect` 내부 함수는 cleanup함수를 return해야 합니다. 그러나 위 코드와 같이 비동기 함수를 사용하면 cleanup 함수가 아니라 Promise 객체를 return하기 때문에 비동기 함수사용을 추천드리지 않습니다 !!ㅜㅜㅜ

2022-08-17 17:22 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +      <SubmitButton onClick={requestJoin} disable={isAlreadyJoined}>
`SubmitButton` 또한 `Title` 컴포넌트와 동일하게 스스로 화면에 가운데 정렬하려는 특성을 가지고 있습니다.
`R1` component로 감싸져 있기 때문인데요..
marginAuto={false}를 prop에 추가하시면 감싸지지 않습니다 !!

2022-08-18 07:37 UTC, GrasshopperBears commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
이 경우 무슨 문구를 띄워야 할까요?

2022-08-18 07:41 UTC, GrasshopperBears commented on src/components/Search/SideResult.jsx
> +                }}
데스크탑 환경 말씀하시는 거 맞죠?

2022-08-18 07:47 UTC, GrasshopperBears commented on src/components/Search/RoomSelectionModal.jsx
> +      <SubmitButton onClick={requestJoin} disable={isAlreadyJoined}>
아 위에 버튼 잘리는 문제는 이거 때문인 것 같네요! maxWidth 조건 다시 없애고 이렇게 수정하겠습니다 :)

2022-08-18 07:50 UTC, GrasshopperBears commented on src/components/common/RLayout.jsx
> +          maxWidth: "100%",
제거했습니다!

2022-08-18 08:40 UTC, GrasshopperBears commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
그리고 이런 방은 아예 표시하지 않는 옵션은 어떻게 생각하시나요?

2022-08-18 11:28 UTC, 14KGun commented on src/components/Search/SideResult.jsx
> +                }}
아아! 맞습니다!

2022-08-18 11:35 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
아예 표시하지 않는 것이 default가 되어야 할 것 같구,
나중에 검색 옵션에서 남은 인원이 0명인 방을 포함하여 검색할 수 있도록 하면 좋을 것 같아요.
front에서 처리하기에는 비효율적인 것 같고, API에서 처리되었으면 합니다. API가 수정되어야 할것 같네요.. (@withSang)

일단 남은 인원이 0명일 때와 방이 `null`일 때는, "참여할 수 없습니다" 문구가 어떠할까요???

2022-08-18 11:38 UTC, 14KGun commented on src/components/Search/SideResult.jsx
> +                }}
모바일 화면일 때, Room 컴포넌트의 배경이 보라색이 되어야 합니다!

<img width="453" alt="스크린샷 2022-08-18 오후 8 37 40" src="https://user-images.githubusercontent.com/69258815/185385833-30f53373-90fc-4a8f-9ee7-f9abc3c68df9.png">

가

<img width="423" alt="스크린샷 2022-08-18 오후 8 37 52" src="https://user-images.githubusercontent.com/69258815/185385898-5e64d883-3faf-4e1b-83f0-9f36489746cc.png">

처럼 배경색이 수정되되어야 할 것 같아요!!

2022-08-18 11:39 UTC, GrasshopperBears commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
뭔가 이유(자리/정원/인원 다 찼음)가 포함돼야 사용자가 이상하게 느끼지 않을 것 같아요

2022-08-18 11:48 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
API를 수정하고 나중에 검색 정렬 이슈에 추가시키는 것이 좋을 것 같습니다!

2022-08-18 11:57 UTC, 14KGun commented on src/components/Search/RoomSelectionModal.jsx
> +        {isAlreadyJoined ? "이미 참여 중입니다" : "참여 신청"}
> 

그러면 저는 "인원이 0명인 방은 참여할 수 없습니다"가 좋을 것 같네용

2022-08-18 11:59 UTC, 14KGun approved these changes
수고하셨습니다!! 👍

2022-08-18 13:39 UTC, merged