#184 refactoring room component
sparcs-kaist/taxi-front pull request #194
Opened 2022-08-19 18:52 UTC by 0ev

# Summary 

It closes #184 

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 
정산완료 밑 남은 인원을 태그 형식으로 보여줌
<img width="283" alt="image" src="https://user-images.githubusercontent.com/63383967/185687428-7da998b2-178b-4c7a-b859-ff56d2f2a680.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/63383967/185687538-9fa48d31-55bb-49da-857f-4ece97976807.png">

2022-08-20 08:45 UTC, 14KGun commented
https://www.notion.so/sparcs/Commit-Message-Convention-0b06ba60535146a9b72dc08cd469ff0c

Commit Convention 참고해주세요~~

2022-08-20 11:22 UTC, 14KGun commented
`common/room/RoomElement.jsx`와 `RoomElement.css`는 이제 사용하지 않으니 지우셔도 될 것 같습니다

2022-08-20 11:29 UTC, 14KGun requested changes
수고하셨습니다~~~
다만 back room api가 수정되면 제작업 부탁드립니다 ㅜㅜ

2022-08-20 11:29 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +      "0px 1.5px 1px -0.5px rgba(110, 54, 120, 0.05), 0px 2.5px 1px -0.5px rgba(110, 54, 120, 0.03), 0px 2px 3px -1px rgba(110, 54, 120, 0.11)",
피그마를 보니 `props.theme`가 `purple`일 때와 `white`일 때, `boxShadow`를 다르게 줘야 할 것 같네용
<img width="427" alt="스크린샷 2022-08-20 오후 8 26 27" src="https://user-images.githubusercontent.com/69258815/185743808-4e1eef7e-e8e2-45d1-a39a-5c7e061d84f1.png">
<img width="420" alt="스크린샷 2022-08-20 오후 8 26 13" src="https://user-images.githubusercontent.com/69258815/185743804-10c9d876-109f-47d0-b783-7918331355c5.png">

2022-08-20 11:29 UTC, 14KGun commented on src/components/common/room/Room.jsx
>    const styleName = {
`paddingRight`는 지우셔도 될 것 같아요!
 - 피그마 디자인
    <img width="547" alt="스크린샷 2022-08-20 오후 8 28 15" src="https://user-images.githubusercontent.com/69258815/185743861-04b10f68-b9fa-41fb-991b-a0d937fb2496.png">

2022-08-20 16:22 UTC, GrasshopperBears reviewed
수고하셨습니다!

2022-08-20 16:22 UTC, GrasshopperBears commented on src/components/common/room/Room.jsx
> +  const tagStyle = {
다른 스타일 변수와 맞춰 `styleTag`로 변수명을 바꾸면 좋을 것 같습니다 :)

2022-08-20 16:22 UTC, GrasshopperBears commented on src/components/common/room/Room.jsx
> +        {props.data.maxPartLength - props.data.part?.length} 명
part가 없는 경우가 있을까요? 그리고 있다면 `props.data.maxPartLength - (props.data.part?.length ?? 0)`과 같이 계산해야 오류가 나지 않을 것 같습니다. (number - undefined 형태가 되기 때문에)

2022-08-20 16:25 UTC, withSang approved these changes
수고하셨습니다!! 네 @14KGun 님 말씀처럼 제가 room API 다시 작업중이기는 한데요, `isSettlement` 타입이 Boolean에서 String으로 바뀌는 거라서 `Room.jsx`에서 더 수정하실 것은 없어 보여요!

2022-08-24 12:47 UTC, 0ev commented on src/components/common/room/Room.jsx
> +      "0px 1.5px 1px -0.5px rgba(110, 54, 120, 0.05), 0px 2.5px 1px -0.5px rgba(110, 54, 120, 0.03), 0px 2px 3px -1px rgba(110, 54, 120, 0.11)",
앗 그렇네요! 감사합니다!

2022-08-24 12:54 UTC, 0ev commented on src/components/common/room/Room.jsx
>    const styleName = {
아예 없에면 완전히 오른쪽으로 붙어버려서 5px로 줄였습니다!

2022-08-24 12:55 UTC, 0ev commented on src/components/common/room/Room.jsx
> +  const tagStyle = {
바꾸었습니다!

2022-08-24 12:57 UTC, 0ev commented on src/components/common/room/Room.jsx
> +        {props.data.maxPartLength - props.data.part?.length} 명
data가 있으면 part가 무조건 있는게 맞는거 같아요!
밑에와 같이 
`props.data?.maxPartLength - props.data?.part.length`
이렇게 수정했습니다!

2022-08-24 13:04 UTC, 0ev commented on src/components/common/room/Room.jsx
> +      "0px 1.5px 1px -0.5px rgba(110, 54, 120, 0.05), 0px 2.5px 1px -0.5px rgba(110, 54, 120, 0.03), 0px 2px 3px -1px rgba(110, 54, 120, 0.11)",
`    boxShadow:
      props.theme == "purple"
        ? "0px 1.5px 1px -0.5px rgba(110, 54, 120, 0.05), 0px 2.5px 1px -0.5px rgba(110, 54, 120, 0.03), 0px 2px 3px -1px rgba(110, 54, 120, 0.11)"
        : "inset 1px 1px 2.5px -1px rgba(110, 54, 120, 0.1)",`

다음과 같이 수정하였습니다!

2022-08-24 13:12 UTC, withSang approved these changes
오 드디어 roomElement가 없어졌군요 👍

2022-08-25 15:53 UTC, 14KGun requested changes
수고하셨습니다 !!

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +    <div style={props.style}>
style은 `NumLeftTag`내부에서 정의하고 `theme`를 props로 넘겨주는 것이 좋을 것 같아요!

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +  const sent = props.users.filter((user) => user.isSettlement == "sent");
`==`를 `===`으로 수정 부탁드립니당

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +      {person()}
컴포넌트 안에서 컴포넌트를 선언하는 것 처럼 보여집니다.
```
let isDone = null;
if (~~~~) isDone = (<div/>)
else if (~~~~) isDone = (<div/>)
```
아니면 
```
const isDone = condition ? <div/> : <div/>;
```
방식 추천드립니다.

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +        <div style={props.style}>
마찬가지로 style은 `IsDoneTag`내부에서 정의하고 `theme`를 props로 넘겨주는 것이 좋을 것 같아요!

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +    } else if (paid.length + sent.length === props.users.length) {
"정산 완료" 태그는 자기 자신의 정산 완료 여부를 나타내어야 할 것이라고 생각했는데,
이렇게 해석될 수도 있네요....

2022-08-25 15:53 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +      return <div></div>;
`null`이 더 좋을 것 같네용

2022-08-27 10:42 UTC, 0ev commented on src/components/common/room/Room.jsx
> +    } else if (paid.length + sent.length === props.users.length) {
앗 그러면 다시 그렇게 바꿀까요?

2022-08-27 10:43 UTC, 0ev commented on src/components/common/room/Room.jsx
> +        <div style={props.style}>
수정하였습니다!

2022-08-27 10:43 UTC, 0ev commented on src/components/common/room/Room.jsx
> +      {person()}
수정하였습니다!

2022-08-27 10:45 UTC, 0ev commented on src/components/common/room/Room.jsx
> +  const sent = props.users.filter((user) => user.isSettlement == "sent");
수정하였습니다!

2022-08-27 10:45 UTC, 0ev commented on src/components/common/room/Room.jsx
> +    <div style={props.style}>
수정하였습니다!

2022-08-27 10:47 UTC, 0ev commented on src/components/common/room/Room.jsx
> +      return <div></div>;
수정하였습니다!

2022-08-27 14:03 UTC, 14KGun commented on src/components/common/room/Room.jsx
> +    } else if (paid.length + sent.length === props.users.length) {
회의에서 논해야 할 듯 합니다...!!

2022-08-27 14:26 UTC, 14KGun approved these changes
수고하셨습니다 ~~~
Conflict 해결하시고 머지하시면 될 것 같아요~~

2022-08-27 15:49 UTC, merged