#217 use query on search
sparcs-kaist/taxi-front pull request #227
Opened 2022-09-09 11:44 UTC by GrasshopperBears

# Summary 

It closes #217

- 검색시 url 쿼리를 이용합니다
- 변경된 flow는 아래와 같습니다.
  ```
  / 혹은 /search
  -> 검색 조건 선택
  -> 검색 버튼 클릭할 경우 조건을 query에 포함해 새로운 url로 이동
  -> url이 변경될 경우 effect 함수 내에서 API 요청
  ```
- 이제 뒤로가가를 할 경우 검색조건이 유지됩니다.

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

https://user-images.githubusercontent.com/34625313/189342523-ca7bfbc1-82fc-42ee-b9f2-6acf7a46534f.mov

# Further Work 

- query를 다양한 방식으로 활용할 수도 있을 것 같습니다

2022-09-11 01:43 UTC, 14KGun requested changes
수고하셨습니다 !!!!! 👍 👍

2022-09-11 01:43 UTC, 14KGun commented on src/components/common/roomOptions/Place.jsx
> +  console.log(props.value, taxiLocation);
지우셔야 할 것 같아요 😢

2022-09-11 01:43 UTC, 14KGun commented on src/components/Search/Search.jsx
> +    setPlace[(null, null)];
괄호가 반대 아닌가용??

2022-09-11 01:43 UTC, 14KGun commented on src/components/Search/Search.jsx
> +      ]);
Date 객체 보다는 moment 객체를 사용하는 것이 코드 통일성이 더 좋아질 것 같은데,
(필수는 아님..!!)
어떻게 생각하시는지요...???

2022-09-11 01:43 UTC, 14KGun commented on src/components/Search/Search.jsx
> +      valuePlace[0] === valuePlace[1]
`AddRoom` 컴포넌트의 if문도 동일하게 바꾸어줘야 할 것 같아요!!
`AddRoom`이 작동을 안합니다 ㅜㅜㅜ

<img width="790" alt="스크린샷 2022-09-11 오전 10 42 43" src="https://user-images.githubusercontent.com/69258815/189508086-c7425047-94cf-4f33-b5f2-858d9fe20540.png">

2022-09-11 03:50 UTC, GrasshopperBears commented on src/components/Search/Search.jsx
> +    setPlace[(null, null)];
세상에....

2022-09-11 03:56 UTC, GrasshopperBears commented on src/components/Search/Search.jsx
> +      ]);
그게 나을 것 같아요! 반영했습니다 :)

2022-09-12 09:21 UTC, 14KGun approved these changes
수고하셨습니다 ~~~~

2022-09-12 14:10 UTC, merged