#251 add cypress github actions
sparcs-kaist/taxi-front pull request #253
Opened 2022-09-27 14:16 UTC by 0ev

# Summary 

It closes #i251

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

# Further Work 

- Do something...

2022-09-27 14:26 UTC, GrasshopperBears approved these changes
좋네요!

2022-09-27 14:30 UTC, GrasshopperBears requested changes
npm start를 어딘가에서 해줘야 할 것 같아요

2022-10-04 15:00 UTC, 0ev commented
Test 자동실행을 완성하였습니다!
Artifact에서 cypress를 실행시킨 영상을 볼 수 있습니다.

2022-10-05 10:15 UTC, 14KGun commented
<img src="https://user-images.githubusercontent.com/69258815/194037068-b478b0aa-2562-45a9-9003-5f9b66981ebf.png">

수고하셨습니다!!
테스트 실패하는 것 같은데.

<img src="https://user-images.githubusercontent.com/69258815/194037269-c3880052-1d0d-48c9-8e92-88d5f5f20211.png">

이것도 분석 가능할까요?

@0ev

2022-10-06 06:14 UTC, 14KGun requested changes
수고하셨습니다!!

통과 안되는 테스트 케이스 분석해주세요 ㅜㅜ

2023-03-09 04:51 UTC, closed without merging