#360 모달이 비활성화 상태일 때 unmount 수정 제안
sparcs-kaist/taxi-front pull request #391
Opened 2022-11-16 10:52 UTC by 14KGun

# Summary 

It closes #360 , #361

2022-11-17 02:50 UTC, imYourChoi requested changes
useDelay 따로 빼는 방법 좋은것 같아요

2022-11-17 02:50 UTC, imYourChoi commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
이렇게 하면 여전히 창이 뜰때는 애니메이션이 안먹히는거 같아요!

2022-11-17 02:50 UTC, imYourChoi commented on src/hooks/useDelay.tsx
> +): TypeValue => {
`TypeValue`는 그냥 `T`로 바꿔도 괜찮지 않을까요?

2022-11-17 06:23 UTC, 14KGun commented on src/hooks/useDelay.tsx
> +): TypeValue => {
그렇군요.. 수정했습니다 ~

2022-11-17 13:33 UTC, 14KGun commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
아!! 이해 했습니다 ~~

2022-11-17 13:37 UTC, 14KGun commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
`Modal` 컴포넌트 수정으로 해결해 봤는데 어떠신가요??

2022-11-18 05:01 UTC, imYourChoi commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
@14KGun 오호 좋은것 같습니다! 근데 저희 생각해보니 shouldMount 자체를 Modal 안으로 넣으면 다른 modal들도 똑같이 작동하지 않을까요?

2022-11-20 13:55 UTC, imYourChoi commented on src/hooks/useDelay.tsx
> +const useDelay = <T,>(value: T, isValid: boolean, delayTime: number): T => {
value와 isValid를 따로 두는 이유가 있을까요

2022-11-20 13:55 UTC, imYourChoi commented on src/hooks/useDelay.tsx
> +  const valueRef = useRef(value);
따로 ref를 두는 이유도 궁금합니다

2022-11-21 14:59 UTC, imYourChoi commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
네네 AlertProvider가 아니라 Modal 안으로 넣자는 얘기였습니다. 제가 작업해서 커밋 날려볼게요

2022-11-21 23:19 UTC, 14KGun commented on src/components/Skeleton/AlertProvider.jsx
> +      display={!!message}
좋은 것 같습니다~ 감사합니다

2022-11-22 01:57 UTC, 14KGun commented on src/hooks/useDelay.tsx
> +const useDelay = <T,>(value: T, isValid: boolean, delayTime: number): T => {
아직까지는 `value`가 `isValid`과 같은 의미로 사용되는 경우 밖에는 없으나
`value`가 `boolean` 값이 아니더라도 `useDelay`를 사용할 수 있도록 해보았습니다.

`useDelay('hello', true, 150)` 이런 식으로 사용할 수 있도록요 !

2022-11-22 03:00 UTC, 14KGun commented on src/hooks/useDelay.tsx
> +  const valueRef = useRef(value);
`value`와 `delayedValue`가 서로 비동기적으로 변하고 서로 간의 `delay`도 있기 때문에,
최종적으로 훅에 요청한 `value`가 무엇인지 알기 위해서 사용하였습니다

2022-11-22 04:06 UTC, 14KGun commented on src/hooks/useDelay.tsx
> +  const valueRef = useRef(value);
이전 `value`가 `delay` 시간 동안 변경되지 않았는데,
훅에서 `value`가 변경되었을 때 대처하기 위해 ref 사용하였습니다.

2022-11-22 04:22 UTC, imYourChoi commented on src/hooks/useDelay.tsx
> +  const valueRef = useRef(value);
https://github.com/sparcs-kaist/taxi-front/pull/361#discussion_r1017566998

진우님이 얘기하신 케이스를 해결하기위한것으로 보이는데 제가 맞게 이해한건가여~

2022-11-22 04:30 UTC, imYourChoi commented
@14KGun 수정사항 확인 부탁드립니다~

2022-11-22 04:47 UTC, 14KGun commented on src/hooks/useDelay.tsx
> +  const valueRef = useRef(value);
오 맞습니다 ~~!!

2022-11-22 06:33 UTC, 14KGun commented on src/components/common/modal/Modal.jsx
> +  useEffect(() => setDisplay(props.display), [shouldMount]);
```suggestion
  useEffect(() => setDisplay(shouldMount), [shouldMount]);
```

useEffect 안에도 `shouldMount` 로 바뀌어야 하지 않을까요?

2022-11-22 06:33 UTC, 14KGun commented on src/components/common/modal/Modal.jsx
> +    opacity: props.display ? (display ? 1 : 0) : 0,
음.. 바꾸신 이유가 뭔가요??? 😮

2022-11-22 14:13 UTC, merged