#403 random placeholder for new room
sparcs-kaist/taxi-front pull request #404
Opened 2022-11-22 14:29 UTC by 0ev

# Summary 

It closes #issue_number

# Images or Screenshots 

# Further Work 

- Do something...

2022-11-22 18:14 UTC, imYourChoi requested changes
👍🏻

2022-11-28 16:35 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +        name: valueName ? valueName : randomName,
그 valueName 이 ""일때 true로 뜨더라구요 null 만 감지하는것 같아요

2022-11-28 16:36 UTC, 0ev commented on src/components/Search/Search.jsx
> +    setCookie("defaultFromTo", valuePlace);
앗 죄송합니다 이 부분 수정하겠습니다

2022-11-28 16:36 UTC, 0ev commented on src/components/Search/Search.jsx
> +
음 만료 기한을 로그인 기간이랑 동일하게 추가하겠습니다

2022-11-28 16:37 UTC, 0ev commented on src/components/Search/Search.jsx
> +
개설한 방을 검색하지는 않을 것 같아서 추가하지 않았습니다

2022-11-28 16:37 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +    ];
빼도록 하겠습니다

2022-11-29 04:30 UTC, imYourChoi commented on src/components/AddRoom/AddRoom.tsx
> +        name: valueName ? valueName : randomName,
아 그러네요

2022-11-29 04:32 UTC, imYourChoi commented on src/components/Search/Search.jsx
> +
아 수정해야겠다는 뜻이 아니고 혹시 저렇게 둬도 괜찮은지 물어본겁니다🙂

2022-11-29 04:37 UTC, imYourChoi commented on src/components/Search/Search.jsx
> +
바로는 아니더라도 자주 검색하는 장소가 있을것 같아서 넣어도 괜찮지 않을까요?

2022-11-29 13:57 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +    ];
수정 완료했습니다!

2022-11-29 13:57 UTC, 0ev commented on src/components/Search/Search.jsx
> +
수정 완료했습니다!

2022-12-01 11:27 UTC, 14KGun commented on src/components/AddRoom/AddRoom.tsx
> +    randomRoomName[Math.floor(Math.random() * randomRoomName.length)]
`randomRoomName[Math.floor(Math.random() * randomRoomName.length)]` 자체를 `static/randomRoomName` 파일 내부에 함수로 만들어도 되지 않을까요?

2022-12-01 11:27 UTC, 14KGun commented on src/static/randomRoomName.js
> +];
`{출발지} {도착지}`가 포함될 수 있는 format string 도 포함할 수 있도록 회의에서 이야기 나오지 않았나요?

2022-12-02 14:12 UTC, GrasshopperBears commented on src/static/randomRoomName.js
> +];
이야기는 나왔는데 회의록 보면 결론은 `여러 랜덤 이름 자동으로 placeholder`였습니다ㅜ

2022-12-02 19:32 UTC, 14KGun commented on src/static/randomRoomName.js
> +];
아 그렇군요 : )

2023-01-05 07:36 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +    randomRoomName[Math.floor(Math.random() * randomRoomName.length)]
늦어서 죄송합니다 수정 완료했습니다!

2023-01-05 07:38 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +  const [cookies, setCookie] = useCookies(["defaultFromTo"]);
늦어서 정말 죄송합니다. 통일했습니다!

2023-01-06 08:58 UTC, 14KGun commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
`cookies?.defaultFromTo?.[0] && cookies?.defaultFromTo?.[1]` 로 대체될 수 있을 것 같아요

2023-01-06 08:58 UTC, 14KGun commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
그리고 cookies.defaultFromTo[0]와 cookies.defaultFromTo[1]이 place 리스트에 포함되어 있는지 확인하는 과정도 조건문 안에 있으면 더 좋을 것 같아요!

2023-01-06 08:58 UTC, 14KGun commented on src/components/AddRoom/AddRoom.tsx
> +  const [randomName, setRandomName] = useState(randomRoomName);
`setRandomName` 함수가 쓰이지 않는데 `randomName`이 state로 쓰이지 않아도 될 것 같습니다.

2023-01-06 12:23 UTC, imYourChoi reviewed
👍🏻

2023-01-06 12:23 UTC, imYourChoi commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
`valuePlace`를 쿠키에 넣을 때부터 출발지랑 도착지 둘 다 있을때만 넣어줘서 `[0]`이랑 `[1]` 둘 다 검사 안해도 되지 않을까요

2023-01-06 12:23 UTC, imYourChoi commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
그리고 장소가 place 리스트 안에 있는지 확인하는 거는 `Place.jsx` 컴포넌트 안에서 하는게 좋을거 같아요!

2023-01-06 12:23 UTC, imYourChoi commented on src/components/Search/Search.jsx
> +      : [null, null];
여기도 바꾸면 좋겠네욤

2023-01-18 11:32 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
`cookies?.defaultFromTo?.[0] && cookies?.defaultFromTo?.[1]` 로 수정했습니다
추가로 Place.jsx에서 이미 find가 undefined일 경우에 처리가 되고 있기 때문에 문제가 생기지 않을 것 같습니다

2023-01-18 11:34 UTC, 0ev commented on src/components/AddRoom/AddRoom.tsx
> +  const [randomName, setRandomName] = useState(randomRoomName);
수정했습니다

2023-01-18 11:37 UTC, 0ev commented on src/components/Search/Search.jsx
> +      : [null, null];
건님이 제안하신 `cookies?.defaultFromTo?.[0] && cookies?.defaultFromTo?.[1]`으로 수정하였습니다. 또한 쿠키에  문제가 생겼을때 (누가 임의적으로 수정 등) 사이트가 터지면 안되서 둘 다 확인하면 좋을 것 같습니다

2023-01-18 14:51 UTC, 14KGun approved these changes
👍 수고하셨습니당

2023-01-18 14:52 UTC, 14KGun commented on src/components/AddRoom/AddRoom.tsx
> +      cookies.defaultFromTo[1]
@imYourChoi 제 의견도 혹시 모를 클라이언트가 직접 쿠키 수정할 가능성 대비해서 둘 다 있는지 확인하는 것이 좋을 것 같아요!!

2023-01-21 16:39 UTC, imYourChoi commented on src/components/Search/Search.jsx
> +      : [null, null];
아하 그런 경우가 있겠네요 👍🏻

2023-01-21 16:40 UTC, imYourChoi approved these changes
👍🏻👍🏻

2023-01-22 00:17 UTC, merged