아이폰 모달 스크롤 오류 해결
sparcs-kaist/taxi-front pull request #405
Opened 2022-11-22 14:49 UTC by GrasshopperBears

# Summary 

- `useDisableScroll`에서 body의 `position`을 `fixed`로 설정해 해결했습니다.

It closes #356 

# Images or Screenshots 

https://user-images.githubusercontent.com/34625313/203344241-f060c752-104c-49d4-986f-e6e94a76ae5e.mp4

2022-11-23 06:17 UTC, GrasshopperBears commented
> `useDisableScroll()` 이 지금 `/components/common/modal/Modal.jsx` 이랑 `/components/common/roomOptions/Popup.tsx`에서 쓰이는데 두 컴포넌트 안에서 `useDisableScroll()` 지우고 대신에 `<RLayout.Popup />` 안에서 쓰면 되는 것 아닌가요?

이건 무슨 말씀이시죠?!

2022-11-23 07:17 UTC, imYourChoi commented
@GrasshopperBears 저희 지금 검색 옵션에 있는 모달은 `Popup.tsx`를 쓰고 마이페이지에서는 `Modal.jsx`를 쓰는데 두 컴포넌트 모두 `RLayout.Popup`을 사용합니다. 그래서 `useDisableScroll`으ㅡㄹ 그 안으로 옮기자는 뜻 같습니다.
@14KGun 어차피 두 컴포넌트 통합하기로 했고 useDisableScroll 쓰려면 `display` 값이 필요해서 이걸 굳이 `RLayout`에 props로 넘겨주는건 번거로운 것 같습니다. 그리고 `RLayout` 자체는 레이아웃 크기만 처리하는 pure한 컴포넌트로 남기는게 좋을것 같다는게 제 개인적인 생각입니다. 이름부터가 `layout`이니까요

2022-11-23 07:28 UTC, 14KGun commented
> @GrasshopperBears 저희 지금 검색 옵션에 있는 모달은 `Popup.tsx`를 쓰고 마이페이지에서는 `Modal.jsx`를 쓰는데 두 컴포넌트 모두 `RLayout.Popup`을 사용합니다. 그래서 `useDisableScroll`으ㅡㄹ 그 안으로 옮기자는 뜻 같습니다. @14KGun 어차피 두 컴포넌트 통합하기로 했고 useDisableScroll 쓰려면 `display` 값이 필요해서 이걸 굳이 `RLayout`에 props로 넘겨주는건 번거로운 것 같습니다. 그리고 `RLayout` 자체는 레이아웃 크기만 처리하는 pure한 컴포넌트로 남기는게 좋을것 같다는게 제 개인적인 생각입니다. 이름부터가 `layout`이니까요

좋은 것 같습니다!! https://github.com/sparcs-kaist/taxi-front/issues/291 작업을 언젠가는 해야겠네요

2022-11-25 04:35 UTC, GrasshopperBears commented
@imYourChoi 깨지는 문제 수정했습니다~

2022-11-25 08:20 UTC, 14KGun approved these changes
LGTM!! 👍

2022-11-25 08:20 UTC, 14KGun commented on src/hooks/useDisableScroll.tsx
>  };
근데, 저희 모달이 한 개가 아니라 여러 개가 같이 뜰 일은 없겠죠?

2022-11-25 09:09 UTC, 14KGun commented on src/hooks/useDisableScroll.tsx
>  };
@GrasshopperBears 마이페이지에서 수정하기 모달 띄우고, 프로필 사진 수정하면 모달 2개 띄어져서
앞에 있는 모달 닫히면, `"overflow"`가 `"unset"` 되지 않을까요??

2022-11-25 09:09 UTC, 14KGun commented on src/hooks/useDisableScroll.tsx
>  };
이거 해결하려면 글로벌 스테이트 사용해야 하나요?? ㅋㅋㅋ

2022-11-25 09:14 UTC, GrasshopperBears commented on src/hooks/useDisableScroll.tsx
>  };
허허 그렇네요. 지금 생각나는 해결 방안으로는
- `disable`를 parameter로 받고
- if문에 `&& !disable` 조건 추가,
- 순서가 2번째 이상인 모달(더 큰 건 없겠지만?)인 경우 이 파라미터를 false로 설정
입니다

2022-11-25 16:22 UTC, imYourChoi commented on src/hooks/useDisableScroll.tsx
>  };
@GrasshopperBears 근데 그렇게 되면 지금 `PopupModify`에서 setAlert할 때부터 그러한 정보를 전해주거나 `AlertProvider`에서 설정된 alert message가 `프로필 사진이 변경되었습니다`인 경우를 필터링해서 `Modal`에 넘겨주고 거기서 또 `useDisableScroll`에 넘겨줘야 될것 같은데 상당히 깔끔하지가 않은것 같습니다. 다른 방법으로는 Picker에서의 이슈처럼 Modal에 class 이름 붙히고 `document.getElementsByClassName`을 통해 모달이 여러개인 경우 비활성화하는 방법이 있을것 같은데 또 다른 방법이 있을까요?

2022-11-26 01:48 UTC, 14KGun commented on src/hooks/useDisableScroll.tsx
>  };
글로벌 스테이트로 띄어져 있는 모달 개수를 관리하거나, `"skeleton-container"`의 attribute에 띄어져 있는 모달 개수를 추가하면 어떨까요?

2022-11-26 02:57 UTC, 14KGun commented
@GrasshopperBears 모달 띄우면, body가 맨 위로 스크롤되어서 올라가는 것 같아요.

2022-11-26 07:23 UTC, GrasshopperBears commented
> @GrasshopperBears 근데 그렇게 되면 지금 `PopupModify`에서 setAlert할 때부터 그러한 정보를 전해주거나 `AlertProvider`에서 설정된 alert message가 `프로필 사진이 변경되었습니다`인 경우를 필터링해서 `Modal`에 넘겨주고 거기서 또 `useDisableScroll`에 넘겨줘야 될것 같은데 상당히 깔끔하지가 않은것 같습니다. 다른 방법으로는 Picker에서의 이슈처럼 Modal에 class 이름 붙히고 `document.getElementsByClassName`을 통해 모달이 여러개인 경우 비활성화하는 방법이 있을것 같은데 또 다른 방법이 있을까요?

@imYourChoi https://github.com/sparcs-kaist/taxi-front/pull/391 이거 작업돼서 괜찮은 방법 같아보이네요

이 이슈 어렵네요 정말 어려워요ㅠㅠㅠㅠ

2022-11-26 07:26 UTC, imYourChoi commented
> @GrasshopperBears 모달 띄우면, body가 맨 위로 스크롤되어서 올라가는 것 같아요.

아 맞아요.. 이거 때문에 이 방법 못썼던것 같아요.. 진짜 어렵네요ㅠㅠ

2022-11-26 07:29 UTC, imYourChoi commented
이게 뭔가 oveflow나 position이 아니라 근본적인 문제가 html, body, root에 height 100%가 설정이 되어 있는데 이게 아이폰에서 주소바가 사라지면 100%가 즉각적으로 화면을 채우는 높이로 반응하지 않아서 스크롤이 되는것 같습니다. 이 부분의 해결책이 찾으면 많은데 어떤 걸 적용해도 뭔가 잘 안되는 것 같아서 어렵네요..

2022-11-26 07:32 UTC, imYourChoi commented on src/hooks/useDisableScroll.tsx
>  };
글로벌은 너무 과한것 같고 두번째 해결책은 괜찮은것 같네요!

2022-11-26 07:35 UTC, GrasshopperBears commented
근데 생각해보니 모달 2개 이상인 경우 생각하면 useDisableScroll hook 로직 자체가 잘못된 것 아닌가요?

2022-11-26 07:43 UTC, imYourChoi commented
그렇긴 하죠. 처음에 모달 2개 띄우는 경우를 생각을 못했네요. 가장 좋은 방법으로는 프로필 사진이 변경 되었을때 알림을 안띄우고 다른 방식으로 알려주도록 변경하는 수도 있는 것 같아요. 사실 모달을 2개 띄우는 방식 자체가 디자인적으로 좀 찜찜하기도 했고 별로 직관적이지 않은 것 같아서요. 어떻게 생각하세요? @14KGun @GrasshopperBears

2022-11-26 08:08 UTC, GrasshopperBears commented
그러면 더 좋을 것 같긴 합니다....ㅎㅎ

2022-11-26 08:12 UTC, GrasshopperBears commented
우선 다음 링크 참고해서 다른 방식으로 해결해봤습니다. 확인 부탁드릴게요 :)
https://pqina.nl/blog/how-to-prevent-scrolling-the-page-on-ios-safari/

2022-11-27 01:48 UTC, 14KGun approved these changes
👍

2022-11-27 06:03 UTC, imYourChoi requested changes

2022-11-27 06:03 UTC, imYourChoi commented on src/App.css
> +
```suggestion
/* html.lock-scroll, */
html.lock-scroll body {
  height: calc(var(--window-inner-height) - 1px);
  overflow: hidden;
  box-sizing: border-box;
  touch-action: none;
}
```
@GrasshopperBears @14KGun 이거 이렇게 하면 주소바도 사라지고, 모달 떴을때 body가 맨 위로 스크롤되지도 않는 것 같습니다..! 드디어 해결...?!?!

2022-11-27 22:12 UTC, 14KGun approved these changes

2022-11-27 23:34 UTC, 14KGun commented
> 그렇긴 하죠. 처음에 모달 2개 띄우는 경우를 생각을 못했네요. 가장 좋은 방법으로는 프로필 사진이 변경 되었을때 알림을 안띄우고 다른 방식으로 알려주도록 변경하는 수도 있는 것 같아요. 사실 모달을 2개 띄우는 방식 자체가 디자인적으로 좀 찜찜하기도 했고 별로 직관적이지 않은 것 같아서요. 어떻게 생각하세요? @14KGun @GrasshopperBears

저는 다른 방식으로 변경하는 것 좋은 것 같아요!! 어떻게 해결할지 생각해두신 방안 있으신가요?

2022-11-27 23:35 UTC, 14KGun commented
버그 있어요!!
프로필 사진 수정하였을 때,
알림 모달이 맨 위로 와야 하는데, 수정하기 모달 뒤로 가네요 ㅜㅜ

2022-11-28 03:55 UTC, imYourChoi commented
> > 그렇긴 하죠. 처음에 모달 2개 띄우는 경우를 생각을 못했네요. 가장 좋은 방법으로는 프로필 사진이 변경 되었을때 알림을 안띄우고 다른 방식으로 알려주도록 변경하는 수도 있는 것 같아요. 사실 모달을 2개 띄우는 방식 자체가 디자인적으로 좀 찜찜하기도 했고 별로 직관적이지 않은 것 같아서요. 어떻게 생각하세요? @14KGun @GrasshopperBears
> 
> 저는 다른 방식으로 변경하는 것 좋은 것 같아요!! 어떻게 해결할지 생각해두신 방안 있으신가요?

@14KGun 아래 방식으로 해결했습니다.
https://user-images.githubusercontent.com/84715637/204190689-b918c8d3-ecf6-4139-bd16-0f9c4b429489.mov

2022-11-28 04:54 UTC, imYourChoi approved these changes
👍🏻

2022-11-28 05:23 UTC, merged