Storybook 기능 추가하기
sparcs-kaist/taxi-front pull request #687
Opened 2023-10-26 12:06 UTC by predict-woo

# Summary 

It closes #685 

# Images or Screenshots 
<img width="930" alt="Screenshot 2023-10-26 at 21 06 06" src="https://github.com/sparcs-kaist/taxi-front/assets/63383967/8ea550a6-ad06-4a93-bf05-63bf6fb7738e">

2023-10-30 16:27 UTC, cokia requested changes
고생많으셨습니다 👍

2023-10-30 16:27 UTC, cokia commented on vite.config.js
> +  envPrefix: "REACT_APP_",
envPrefix를 이렇게 쓰기보다는, env 자체에서 프리픽스를 때는게 가독성상 좋아보이는데 어떻게 생각하시나요?

2023-10-30 16:27 UTC, cokia commented on src/tools/toast/index.tsx
> +// import { sendPopupInAppNotificationEventToFlutter } from "@/tools/sendEventToFlutter";
사용하지 않는 임포트는 지우면 좋을 것 같습니다!

2023-10-31 12:13 UTC, predict-woo commented on vite.config.js
> +  envPrefix: "REACT_APP_",
사실 이미 tsconfig에 configoption 아래에  `"jsxImportSource":` "@emotion/react",`으로 들어가있습니다. 이론적으로는 저렇게 넣는 것과 같은 효과여야 하는데, 이상하게 저걸 빼면 jsx파일의 css tag가 인식되지 않습니다....ㅜㅠ

2023-11-02 09:41 UTC, 14KGun commented on src/tools/toast/index.tsx
> +// import { sendPopupInAppNotificationEventToFlutter } from "@/tools/sendEventToFlutter";
`import`해서 사용하는게 맞는 코드인데 앱의 버그로 인해 일단 주석 처리해둔 것이 맞습니다!!
앱의 버그가 해결되면 다시 사용할 코드라 주석처리 해두는 것이 좋을 것 같습니다!

2023-11-02 10:41 UTC, 14KGun commented on src/components/Chat/index.tsx
> -
`prettier`가 `import` 순서를 자동으로 정렬해주어서 [.prettierrc.json](https://github.com/sparcs-kaist/taxi-front/blob/%23685-add-storybook-to-taxi-front/.prettierrc.json) 에서 설정 값 바꿔주어야 할 것 같아요!

https://github.com/sparcs-kaist/taxi-front/blob/890acfde33ee6a41ce94c278a80ac06172cec366/.prettierrc.json#L16-L25

2023-11-02 10:41 UTC, 14KGun commented on src/components/Chat/index.tsx
> -
그럼 각 `import` 정렬 순서 이전이랑 같을 겁니다 ㅎ

2023-11-02 10:41 UTC, 14KGun commented on index.html
혹시 `index.html` 파일 위치를 옮긴 이유가 있을까요?? 🧐 🧐

2023-11-02 10:41 UTC, 14KGun commented on index.html
> +    </script>
제가 이 코드가 필요한 이유를 이해 못했는데.. 추가되어야 하는 이유 설명해주세요 ㅜㅜ (이해가 필요합니다 ㅜㅜ)

2023-11-02 12:17 UTC, predict-woo commented on index.html
안 옮기고 설정을 바꿀 수도 있지만, vite가 기본적으로 index.html을 root에서 찾기 때문에 복잡한 설정을 최대한 줄이려고 root로 옮겼습니다. 필요하다면 다시 public으로 옮길 수 있습니다.

2023-11-02 12:19 UTC, predict-woo commented on index.html
> +    </script>
cra에서는 번들링된 소스가 들어가있는 script tag가 자동으로 inject되는데 vite에서는 안되는 것으로 알고있어요

2023-11-02 12:20 UTC, predict-woo commented on src/components/Chat/index.tsx
> -
감사합니다! 수정하겠습니다

2023-11-02 17:29 UTC, 14KGun commented on .prettierrc.json
> +    "^@/components/|^pages/",
```suggestion
    "^@/components/|^@pages/",
```

"pages" 앞에도 `@`가 붙어야 할 것 같아요

2023-11-02 17:29 UTC, 14KGun commented on tsconfig.json
> +  "references": [{ "path": "./tsconfig.node.json" }]
두 설정 파일을 분리해서 관리하는 이유가 있을까요??
`tsconfig.node.json` 와 `tsconfig.json`을 합쳐서 관리해도 될 것 같아서요

2023-11-07 10:01 UTC, predict-woo commented on .prettierrc.json
> +    "^@/components/|^pages/",
수정했습니다!

2023-11-07 10:05 UTC, predict-woo commented on tsconfig.json
> +  "references": [{ "path": "./tsconfig.node.json" }]
수정했습니다!

2023-11-08 04:00 UTC, imYourChoi commented on tsconfig.json
> +  "references": [{ "path": "./tsconfig.node.json" }]
궁금해서 스윽 놀러왔습니다.
tsconfig.node.json이 아마 vite의 node 환경에 쓰이는 설정들이 들어가 있어서 기본 설정으로 분리가 되어 있는 걸로 알고 있습니다. 그래서 어떤 사람들은 tsconfig.vite.json으로 이룸 바꾸기도 하더라구요. 합쳤을 때 어떤 이슈가 있는지는 모르겠습니다.

2023-11-08 04:17 UTC, 14KGun commented on src/components/Skeleton/index.tsx
> +import Error from "@/pages/Error";
마찬가집니당

2023-11-08 04:17 UTC, 14KGun commented on src/hooks/skeleton/useGoogleAnalyticsEffect.tsx
> +          testMode: nodeEnv,
이거 지우신 이유가 있을까요???

2023-11-08 04:17 UTC, 14KGun commented on src/hooks/skeleton/useI18nextEffect.tsx
> +import nsSearchKO from "@/pages/Search/langs/ko.json";
흠.. 마찬가지입니다.

2023-11-08 04:17 UTC, 14KGun commented on src/hooks/skeleton/useI18nextEffect.tsx
> +    debug: nodeEnv,
이것도 지우신 이유가 있을까요?

2023-11-08 04:17 UTC, 14KGun commented on src/pages/Addroom/index.tsx
> +import { MAX_PARTICIPATION } from "@/pages/Myroom";
마찬가지입니다 ~

2023-11-08 04:17 UTC, 14KGun commented on src/tools/loadenv.ts
> +export const nodeEnv = env.DEV; // automatically provided
흠... vite 에서는 `NODE_ENV` 자동 주입 안되나요???

2023-11-09 12:41 UTC, withSang commented on src/tools/loadenv.ts
> +export const nodeEnv = env.DEV; // automatically provided
> - import.meta.env.DEV: {boolean} 앱이 개발 환경에서 실행 중인지 여부이며, 항상 import.meta.env.PROD와 반대되는 값을 가집니다.

라고 합니다! https://ko.vitejs.dev/guide/env-and-mode.html

2023-11-09 12:42 UTC, withSang commented on src/hooks/skeleton/useI18nextEffect.tsx
> +    debug: nodeEnv,
nodeEnv가 이제 개발환경인지 아닌지를 나타내는 boolean이라 그렇군요.. `nodeEnv`보다 `isDev` 같은 변수명이 더 의미를 잘 담는 것 같다고 생각합니다!

2023-11-09 13:54 UTC, 14KGun commented on src/components/Room/index.stories.tsx
> +  });
이거 `useEffect`로 감싸야 하지 않을까요??

2023-11-10 01:11 UTC, 14KGun approved these changes
LGTM 👍 

수고하셨습니다 ~~ 😄 😄

2023-11-12 04:51 UTC, merged