회원 탈퇴 채널톡 연결 컴포넌트
sparcs-kaist/taxi-front pull request #769
Opened 2024-03-26 11:35 UTC by ybmin

# Summary 

It closes #767 
[https://developers.channel.io/reference/web-channelio-kr](url) 채널톡 개발 문서에 의하면 openChat을 통해 message를 미리 채워서 채팅창을 열게 할 수 있다고 합니다. 

# Images or Screenshots 
![image](https://github.com/sparcs-kaist/taxi-front/assets/47024715/8bbe228d-1640-48db-9805-6a5a778053ad)

# Further Work 
- [ ] 로컬에서 채널톡 api key가 없어서 dev나 기타 방향을 통해 실제로 채팅창이 의도된 방향으로 잘 뜨는지 알아봐야 합니다.
- [ ] 회원 탈퇴 신청 텍스트를 수정해야 합니다.

2024-03-26 12:18 UTC, kmc7468 commented on packages/web/src/pages/Mypage/index.tsx
> +        "스팍스 택시 서비스의 계정 탈퇴를 신청하고 싶습니다.\n신청 사유는 다음과 같습니다:\n",
SPARCS Taxi로 수정 가능할까요?!

2024-04-24 05:29 UTC, predict-woo approved these changes
LGTM!

2024-04-24 15:07 UTC, kmc7468 requested changes

2024-04-24 15:07 UTC, kmc7468 commented on packages/web/src/pages/Mypage/index.tsx
> +  const onClickWithdraw = useCallback(() => {
중요한 부분은 아니긴 한데, 회원 탈퇴는 withdraw보다는 cancel이라는 표현을 더 많이 쓰는 것 같아요! (GPT 피셜) 개인적으로는 withdraw라고 하니 인출이 먼저 생각이 나서.. cancel이라는 표현을 쓰면 가독성이 더 좋아질 것 같습니다.

2024-04-25 06:53 UTC, ybmin commented on packages/web/src/pages/Mypage/index.tsx
> +  const onClickWithdraw = useCallback(() => {
cancel_account로 변경하였습니다

2024-04-30 13:57 UTC, kmc7468 approved these changes
LGTM!

2024-04-30 13:58 UTC, merged