#778 홈 화면 방 팝업에서 참여 중인 방 선택 시 바로가기 버튼 추가
sparcs-kaist/taxi-front pull request #779
Opened 2024-04-02 14:08 UTC by jinhyeonkwon

# Summary 

It closes #778 

packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx 를 수정하여,
1) 이미 참여 중인 방의 경우에도 활성화된 버튼이 나타나도록 하였으며
2) requestJoin 을 수정하여, 해당 버튼을 누르면 history.push를 사용하여 바로 방으로 이동하는 로직을 추가하였습니다.

requestJoin을 수정하면서, 이미 참여 중인 방은 API 호출이 필요 없기에 기존의 코드를 모두 무시하도록 하였습니다. requestJoin의 수정 사항이 적절한지를 중심으로 리뷰해주시면 감사하겠습니다.

# Images or Screenshots 

### 수정 전
![image](https://github.com/sparcs-kaist/taxi-front/assets/121283722/46621351-173f-4879-a6e6-bff56a1d06c0)

### 수정 후
![image](https://github.com/sparcs-kaist/taxi-front/assets/121283722/4981ae19-4571-42f4-9d7e-c11b835c5b48)

# Further Work 

- Do something...

2024-04-07 11:16 UTC, 14KGun approved these changes
LGTM !! 👍

2024-04-08 04:47 UTC, kmc7468 requested changes
수고하셨습니다! LGTM! 사소한 코멘트 2개 남겼는데 확인 부탁드려요.

2024-04-08 04:47 UTC, kmc7468 commented on packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
> +          {isDepart
이 부분은 isDepart && !isAlreadyPart로 안바꿔도 괜찮을까요??

2024-04-08 04:47 UTC, kmc7468 commented on packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
> +    }
여기 아래에 빈 줄이 하나 들어가면 로직이 분리되어 보여서 더 좋을 것 같습니다!

2024-04-08 04:55 UTC, jinhyeonkwon commented on packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
> +          {isDepart
isAlreadyPart 검사를 앞으로 당기려다가 만 것 같은데, 그렇게 하는 게 가장 확실하겠네요! 수정하겠습니다

2024-04-08 04:56 UTC, jinhyeonkwon commented
민찬님 피드백까지 반영했어요!

2024-04-08 04:59 UTC, kmc7468 approved these changes
빠른 피드백 반영 감사합니다!

2024-04-08 05:13 UTC, merged