#805 회원 탈퇴 구현
sparcs-kaist/taxi-front pull request #806
Opened 2024-08-12 09:30 UTC by jinhyeonkwon

# Summary 

It closes #805 

탈퇴에 대응하여

1. 탈퇴하는 기능을 만듭니다. 정산이나 송금이 완료되지 않은 방이 있는 경우, 안내가 표시되며 탈퇴가 불가능합니다.
2. 탈퇴한 유저는 채팅창에서 알아볼 수 있도록 표시합니다. (취소선, 색 변경, 유령 프로필 사진 등)
3. 탈퇴 사용자의 경우, 채팅창의 신고 버튼과 해당 유저를 눌렀을 때 나오는 신고 버튼이 작동하지 않도록 합니다. (신고 관련 문구 수정도 일부 했습니다)

Global한 부분은 아래와 같이 변경되었습니다.
1. global type인 `User`에 `withdraw`라는 field가 추가되었습니다.
2. `AxiosOption` type의 `method`가 `"delete"` 값을 가질 수 있도록 했습니다. (탈퇴를 처리하는 API가, 처음으로 delete method를 쓰게 되었습니다)
3. `LoginInfoType`에 `withdraw` field가 추가되었습니다.
4. `ProfileImageProps`에 `withdraw` field가 추가되었습니다. 추후 호환성에 문제가 생길 것을 대비하여, optional하게 설정하고, 비워두면 Component 코드 쪽에서 false 값을 이용하도록 하였습니다.
5. 탈퇴 후, mypage로 리다이렉션하여 탈퇴 완료를 알리는 alert를 띄웁니다. 백엔드에서 query string이 포함된 url을 받아서 redirect하는 방식입니다. 이 구현을 위해, mypage에서 탈퇴 관련 parameter를 처리하는 코드를 추가하였습니다.
 
# Further Work 
- 개인정보 처리 방침 개정 후, 탈퇴 안내문을 변경하는 PR이 필요합니다.
- 기존의 이벤트 코드를 수정하여 새로운 이벤트를 여는 경우, 회원의 탈퇴를 고려한 수정이 필요합니다.

# Images or Screenshots 
### 메뉴
![image](https://github.com/user-attachments/assets/3dcb66f0-af96-411e-af08-2b07888cc108)
로그인하지 않은 경우에는 아래와 같이 보입니다.
![image](https://github.com/user-attachments/assets/13dea081-217d-4d79-a332-a3a0a3a93b81)

### 탈퇴 모달 (탈퇴 가능할 때)
![image](https://github.com/user-attachments/assets/5ea41452-d9be-4822-bc01-31696e0616c5)
![image](https://github.com/user-attachments/assets/dec8e842-97e8-4e2a-8da0-d6a7703586fd)

### 탈퇴 모달 (탈퇴 불가능할 때)
현재 탈퇴 불가능한 경우는 아래의 한 가지 뿐입니다.
![image](https://github.com/user-attachments/assets/2c6daf94-e793-49a5-a265-f47a7bc30b24)

### 탈퇴한 유저에 관한 표시
![image](https://github.com/user-attachments/assets/d5c6d0ca-ddd7-4365-9a1b-6f6b724a65e1)
![image](https://github.com/user-attachments/assets/cbfe03ce-f30c-4632-aa8a-26da8013a2ef)
![image](https://github.com/user-attachments/assets/23636ecd-12c3-4f8e-867d-2477c30f0bb0)
![image](https://github.com/user-attachments/assets/ff195d77-90a5-4687-8c68-3c3a6a4b3f6c)
![image](https://github.com/user-attachments/assets/8c822570-e2cb-42cd-962a-8d5f3cef4864)

2024-11-21 18:22 UTC, kmc7468 requested changes
수고하셨습니다!

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/hooks/useTaxiAPI/useAxios.tsx
> +  method: "get" | "post" | "delete";
이거 이제는 필요 없을 것 같습니다!

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/pages/Mypage/index.tsx
> +  const onClickCancelAccount = useCallback(
withdraw로 이름 바꿔주면 좋을 것 같습니당

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/pages/Mypage/index.tsx
> +          {userId && (
로그인 안 된 상태에서는 혹시 어떻게 표시될까요?

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/components/User/index.tsx
> +        <ProfileImage url={value.profileImageUrl} withdraw={value.withdraw} />
isWithdrew를 만들어 놓았으니 그걸 쓰면 어떨까요?

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/components/User/index.tsx
> +          <span style={theme.font8} css={{ textDecoration: undefined }}>
혹시 `textDecoration: undefined` 필요한 이유가 뭐였나요..? 뭔가 이유가 있었던 것 같은데 지금 보니 딱히 필요 없는 것 같기도 하구요.. 프론트 어렵군요 ㅠ

2024-11-21 18:22 UTC, kmc7468 commented on packages/web/src/components/User/ProfileImage.tsx
>    }, [url]);
여기 dependency list에 withdraw는 안 넣어도 되나용?

2024-11-26 13:13 UTC, jinhyeonkwon commented on packages/web/src/pages/Mypage/index.tsx
> +          {userId && (
헉 이렇게 되네요
![image](https://github.com/user-attachments/assets/67af5c10-2433-49d1-9d66-8c9d87880755)
이때는 whiteContainer가 안 보이게 수정하겠습니다

2024-11-26 13:16 UTC, jinhyeonkwon commented on packages/web/src/pages/Mypage/index.tsx
> +          {userId && (
이렇게 수정했습니다
![image](https://github.com/user-attachments/assets/13dea081-217d-4d79-a332-a3a0a3a93b81)

2024-11-26 13:24 UTC, jinhyeonkwon commented on packages/web/src/components/User/ProfileImage.tsx
>    }, [url]);
헉 넣어야 하는데 빠뜨린 것 같네요 넣겠습니다

2025-02-05 08:59 UTC, kmc7468 requested changes

2025-02-06 07:56 UTC, kmc7468 approved these changes
LGTM! 수고하셨습니다~~

2025-02-07 14:04 UTC, malloc3141 commented
저도 괜찮은 것 같아요! 고생하셨습니다

2025-02-08 03:50 UTC, merged