#75 Fix Search UI and implement Search
sparcs-kaist/taxi-front pull request #95
Opened 2022-04-26 15:25 UTC by imYourChoi

2022-04-26 15:25 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-27T00:25:34
          
          
            * 메일 제목 : 
[sparcs-kaist/taxi-front] #75 Fix Search UI (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2022-04-27 15:22 UTC, 14KGun reviewed
고생하셨습니다!!!!

2022-04-27 15:22 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-04-28T00:22:18
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] #75 Fix Search UI (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2022-05-03 16:54 UTC, 14KGun requested changes

2022-05-03 16:54 UTC, 14KGun commented on src/components/Search/Search/Search.jsx
> +      setDisable(true);
저희 검색 조건이 아무 것도 없을 때에는 "모든 방 찾기"로 back과 front 둘 다 구현되어야 할 것 같습니다.

2022-05-03 16:54 UTC, 14KGun commented on src/components/Frame/ReactiveLayout/RLayout.jsx
> +export default { useR1state, useR2state, R1, R2, Popup };
usePopupstate를 export하고 있지 않습니다.

2022-05-03 16:54 UTC, 14KGun commented on src/components/Frame/Title/Title.jsx
> +  paddingBottom: "0px",
paddingTop과 paddingBottom은 propTypes과 defaultProps에서 지우셔야 할 것 같아요

2022-05-06 16:03 UTC, imYourChoi commented on src/components/Frame/ReactiveLayout/RLayout.jsx
> +export default { useR1state, useR2state, R1, R2, Popup };
@14KGun 수정하였습니다

2022-05-06 16:03 UTC, imYourChoi commented on src/components/Frame/Title/Title.jsx
> +  paddingBottom: "0px",
@14KGun 수정하였습니다

2022-05-06 16:03 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-05-07T01:03:43
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] #75 Fix Search UI and implement Search (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2022-05-06 16:08 UTC, imYourChoi commented on src/components/Search/Search/Search.jsx
> +      setDisable(true);
@14KGun 백엔드 쪽에서 api 완성되면 추후에 수정하도록 하겠습니다 #111

2022-05-06 16:08 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-05-07T01:08:30
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] #75 Fix Search UI and implement Search (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2022-05-10 09:46 UTC, merged

2022-10-11 08:30 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-05-07T01:03:39
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] #75 Fix Search UI and implement Search (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2022-10-11 08:41 UTC, hyeongjunCho commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2022-05-04T01:54:57
          
          
            * 메일 제목 : 
Re: [sparcs-kaist/taxi-front] #75 Fix Search UI and implement Search (PR #95)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.